image: bradrydzewski/base
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: "influxdb-service"
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/influxdb-service
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    #- latest
    username: $$docker_username
    when:
      branch: 0.10beta
