env:
- REPORT_CARD_GITHUB_STATUS_TOKEN=$$report_card_github_status_token
- REPORT_CARD_GITHUB_REPO_TOKEN=$$report_card_github_repo_token
image: bradrydzewski/base
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: "influxdb-service"
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/influxdb-service
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    #- latest
    username: $$docker_username
    when:
      branch: master
script:
- sudo pip install -q git+https://$REPORT_CARD_GITHUB_REPO_TOKEN@github.com/Clever/report-card.git; GITHUB_API_TOKEN=$REPORT_CARD_GITHUB_STATUS_TOKEN report-card --publish || true
# no tests here
- echo "no tests here"
